project:
  type: website
  output-dir: _site

website:
  title: "My Website"
  favicon: images/randy.png
  page-navigation: true
  page-footer:
    center: "Copyright 2026, Giora Simchoni"
    border: light
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: phd/index.qmd
        text: My PhD for Everyone
  sidebar:
    - title: "My PhD for Everyone"
      contents:
        - phd/index.qmd
        - phd/whats-a-model.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor:
  render-on-save: true
