project:
  type: website
  output-dir: _site

website:
  title: "My Website"
  favicon: images/randy.png
  page-navigation: true
  page-footer:
    center: "Copyright 2026, Giora Simchoni"
    border: light
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: phd/01_index.qmd
        text: My PhD for Everyone
  sidebar:
    - title: "My PhD for Everyone1"
      contents:
        - phd/01_index.qmd
        - phd/02_whats_a_model.qmd
        - phd/03_learning.qmd
        - phd/04_overfitting.qmd
        - phd/05_random_variable.qmd
        - phd/06_rvs_in_a_model.qmd
        - phd/07_a_history_lesson.qmd
        - phd/08_likelihood.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor:
  render-on-save: true
